[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
rustflags = [
    "-C",
    "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C",
    "link-arg=--max-memory=4294967296",
]
